FROM nvidia/cuda:9.0-cudnn7-runtime

RUN echo "root:root" | chpasswd
RUN apt-get update  --fix-missing
RUN apt-get -y install sudo curl git vim zsh unzip imagemagick bzip2 language-pack-ja
RUN apt-get -y install htop xsel

# python env
WORKDIR /usr/local/bin
RUN git clone git://github.com/yyuu/pyenv.git .pyenv

ENV PYENV_ROOT /usr/local/bin/.pyenv
ENV PATH $PATH:$PYENV_ROOT/shims:$PYENV_ROOT/bin

RUN pyenv install anaconda3-5.0.1
RUN pyenv global anaconda3-5.0.1
RUN pyenv rehash

RUN pip install --upgrade pip
RUN pip install opencv-python tqdm h5py keras tensorflow-gpu==1.8 kaggle-cli gym
RUN pip install chainer
RUN pip install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
RUN pip install torchvision


# create user
{% for user in user_list %}
RUN groupadd {{user.name}} -g {{user.uid}} && useradd -m {{user.name}} -u {{user.uid}} -g {{user.uid}}
RUN usermod -s /bin/bash {{user.name}}
RUN echo "{{user.name}}:{{password}}" | chpasswd
{% if user.sudo == "true" %}
RUN gpasswd -a {{user.name}} sudo
{% endif %}
WORKDIR /home/{{user.name}}
RUN sudo -u {{user.name}} touch "{{user.sudo}}"
RUN sudo -u {{user.name}} mkdir -p .ssh
RUN sudo -u {{user.name}} chmod 700 .ssh
RUN sudo -u {{user.name}} touch .ssh/authorized_keys
RUN sudo -u {{user.name}} chmod 600 .ssh/authorized_keys
RUN sudo -u {{user.name}} echo "{{user.pub}}" > .ssh/authorized_keys
RUN sudo -u {{user.name}} echo "export PYENV_ROOT=/usr/local/bin/.pyenv" >> .bashrc
RUN sudo -u {{user.name}} echo "export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH" >> .bashrc
{% endfor %}


WORKDIR /root

# ssh server
RUN apt-get -y install openssh-server
RUN mkdir /var/run/sshd
RUN sed -i -e "s/\#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
EXPOSE 22

# cleanup
RUN apt-get autoremove && apt-get clean

# default shell
CMD /usr/sbin/sshd -D && tail -f /dev/null
